name: Package and Release

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm install
      - name: Add MacOS Certs
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/')
        run: chmod +x add-osx-cert.sh && ./add-osx-cert/sh
        env:
          MAC_CERTS: ${{ secrets.MAC_CERTS }}
          MAC_CERTS_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
      - name: build
        run: npm run make
        env:
          APPLE_ID: ${{ secrets.apple_id }}
          APPLE_PASSWORD: ${{ secrets.apple_password}}
          APPLE_TEAM_ID: ${{ secrets.apple_team_id}}
