name: Build
on: [ push, pull_request ]

jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run make
        env:
          APPLE_ID: ${{ secrets.apple_id }}
          APPLE_PASSWORD: ${{ secrets.apple_password}}
          APPLE_TEAM_ID: ${{ secrets.apple_team_id}}
