name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Add MacOS Certs
        run: echo "Running" && chmod +x ./.github/scripts/add-osx-cert.sh && ./.github/scripts/add-osx-cert.sh
        env:
          MAC_CERTS: ${{ secrets.MAC_CERTS }}
          MAC_CERTS_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
      - name: Install Dependencies
        run: npm install
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.apple_id }}
          APPLE_PASSWORD: ${{ secrets.apple_password}}
          APPLE_TEAM_ID: ${{ secrets.apple_team_id}}
        run: npm run publish
